contact_links:
  - name: 🤔 Questions and Help
    url: https://github.com/FrenkyDema/valorant_change_audio_language/discussions/new?category=q-a
    about: Open a new question in the discussion section.
